fix example
cloudposse/terraform-aws-code-deploy pull request #5
Opened 2021-08-17 10:20 UTC by umihico

## what
* The example was providing `arn` instead of `name` and fixed it.

## why
* To make it work.

2021-08-17 14:22 UTC, max-lobur requested changes
Hi umihico! Thank you for your contribution.

Did you check https://github.com/cloudposse/terraform-aws-alb/blob/master/outputs.tf
if alb_name or alb_dns_name do the job?

2021-08-17 15:28 UTC, nitrocode commented
@max-lobur I think this change was exclusive to the example, no ?

2021-08-18 00:03 UTC, umihico commented
@max-lobur and  nitrocode

Thank you for reviewing. 
There is a way to use `alb_name` in `elb_info` instead of `target_group_pair_info`. I could rewrite something like this.

```
  load_balancer_info = {
    elb_info = {
      name = module.alb.alb_name
    }
    # target_group_pair_info = {
    #   prod_traffic_route = {
    #     listener_arns = [module.alb.http_listener_arn]
    #   }
    #   blue_target_group = {
    #     name = data.aws_lb_target_group.blue.name
    #   }
    #   green_target_group = {
    #     name = aws_lb_target_group.green.name
    #   }
    # }
  }
```

However, I faced this error and failed to apply.
> Error: Error updating CodeDeploy deployment group: InvalidLoadBalancerInfoException: For ECS deployment group, loadBalancerInfo must not contain elbInfo list

I also found references that say `elb_info` is for the classic load balancer, so I guess we need to specify target group names in this ECS with CodeDeploy example.

[Terraform reference](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codedeploy_deployment_group#load_balancer_info-argument-reference)
[AWS CLI command reference](https://docs.aws.amazon.com/cli/latest/reference/deploy/create-deployment-group.html#options)

2022-07-07 20:02 UTC, nitrocode approved these changes

2024-03-02 02:19 UTC, closed without merging